### ISSUE TITLE
Unable to install lib on Windows Azure

### ISSUE THREAD

**Issue by akhilclarion** [vingd/libxml2-python#1]
HI vingd,

I am unable to install libxml2-python on Azure Web App.
On Azure web app, we can install pacakages with pip only, no .exe support.
Please guide me on this.

**Comment by randomir** [comment]
Hi akhilclarion,
this version of `libxml2-python` is our (unofficial) and old/unmaintained snapshot of libxml2. Please consult the official distribution here http://xmlsoft.org/downloads.html.
Also, maybe this can be of use to you: http://www.lfd.uci.edu/~gohlke/pythonlibs/.
